### ISSUE TITLE
on Linux build.py is looking for an old version of python.

### ISSUE THREAD

**Issue by stibinator** [GimelStudio/GimelStudio#196]
**Describe the bug**

**To Reproduce**
Install current version of python
Download GimelStudio source
> python3 build.py

**Expected behavior**
checks for version of python >= 3.9

**Observed behaviour**
checks for ONLY python version 3.9.x

**Desktop (please complete the following information):**
Linux
Python 3.10.12

Editing the build file and just replacing "3.9" with "3.10" seems to work (pending it finishing), maybe a slightly better way of checking for compatible python versions than hard-coding the version number is in order.

**Comment by Correct-Syntax** [comment]
Hi, thanks for opening an issue. I believe the reason for hard-coding  3.9 was because at the time, a few of our dependencies had not yet released packages for Python 3.10. So, yes that could probably be adjusted now.

**Comment by stibinator** [comment]
BTW it didn't end up working, I had to manually add brew to the $PATH, then the openimageio install failed. If I open python I can import OpenImageIO, but the build script fails when it checks for the OpenImageIO path.

**Comment by Correct-Syntax** [comment]
For anyone stumbling upon this issue trying to use the build script: **its probably best not to use the build file method anymore since its outdated and doesn't work many many distros.** 

Instead:

1. Grab the wxpython wheel for your distro from here https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ and install it either by downloading the wheel file, etc. or by installing it from the url. 
2. Then ``pip install -r requirements.txt`` to install the rest of the dependencies.
3. ``cd src`` 
4. ``python3 main.py``

**Comment by Metallicow** [comment]
Ok issue closed, it isn't sometimes the best idea to (python) dictionary and object(hashtable) an object.(period) . Come back to me when you are sober.

**Comment by Correct-Syntax** [comment]
> Ok issue closed, it isn't sometimes the best idea to (python) dictionary and object(hashtable) an object.(period) . Come back to me when you are sober.

@Metallicow, Could you explain what you mean? :shrug:
